In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.sum(axis=1))

[ 6 15]

In [3]:
df = pd.read_csv("employee_data.csv")

In [4]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [5]:
df.loc[0:2]
df.iloc[0:2]

df.loc[0:2, ["Name", "Age"]]
df.iloc[0:2, 1:3]

# Department of 0th row

df.loc[0, "Department"]
df.iloc[0, 3]

'HR'

In [6]:
#Filtering data

df[ df["Salary"] > 50000]
df[ (df["Salary"] > 50000) & (df["Age"] > 30) ] # chaining 

df.iloc[0]

# query
df.query("Salary > 50000")
df.query("Salary > 50000 & Age > 30")   # Chaining

age_val = 30
df.query("Salary > 50000 & Age > @age_val") [["ID" , "Name"]]

   ID   Name
1   2    Bob
3   4  David
4   5    Eva
6   7  Grace
8   9    Ian

In [7]:
# Handling missing values

df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [8]:
df.isnull()
df.isna()   # same functionality as isnull

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [9]:
df.isnull().sum()   #returns the total number of missing values in each column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [10]:
# remove missing values 

df.dropna().copy()  # dropna removes all rows with missing values
df.dropna(axis = 1)  # drops columns with empty values

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [11]:
# filling missing values

df.fillna(0)    # fills all missing values with 0

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)  #fills age column with mean age


cleaned_data["gender"] = cleaned_data["gender"].fillna("Unknown")

income_mean = cleaned_data["income"].mean()
cleaned_data["income"] = cleaned_data["income"].fillna(income_mean)

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  57600.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA  Unknown  58000.0

In [12]:
# forward and backward fill

cleaned_data = df.copy()
cleaned_data["income"] = cleaned_data["income"].ffill() # forward fill

cleaned_data["gender"] = cleaned_data["gender"].bfill() # backward fill

cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [13]:
# Handling duplicate values

df.duplicated() #tells which rows are duplicated

non_duplicated_data = df.drop_duplicates().copy() # drops all duplicate rows

non_duplicated_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [14]:
# handling datatypes
df.dtypes   # returns the datatype of columns

df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")

df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [15]:
# Handling string datas

df["gender"].str.lower()   
df["name"].str.strip(" ")   # strips string from the separator value
df["country"].str.contains("china", case = False)   # checks if a string contains a word/string

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [16]:
#Transforming our data (Feature Engineering)

# 1. apply(fnx) applies a function to a feature/ column
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x: "10%" if x > 60000 else "20%")

# 2. map() maps the features across a column
gender_map = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)

# 3. assign() assigns new values from an existing column to a new column
df2 = df2.assign(new_income=df2["income"] * 1.1)

# 4. replace(old_val, new_val)
df2["country"] = df2["country"].replace("USA", "United States")

# 5. rename(columns/index = { old: new })
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"] # changes name of all the columns
# rename() returns a new DataFrame by default, so assign it back or use inplace=True

df2 = df2.rename(columns={"Income": "Salary"})  # renames columns
# df2 = df2.rename(index={1: "First"})    # renames rows


# 6. sort_values()
# df2.sort_values("Salary", ascending=False)  # ascending=False sorts values in descending order
sorted_df = df2.sort_values(["Salary", "Age"])  # sorts based on salary but age incase incomes are same

# 7. sort_index()
sorted_df = df2.sort_index(ascending=True)

# 8. reset_index()
sorted_df.reset_index() # (drop=True) can be used if we don't want to preserve original index

# 9. Ranking
sorted_df["Salary"] = sorted_df["Salary"].fillna(25000)
sorted_df["Ranking"] = sorted_df["Salary"].rank()   # rank(method: Literal['average', 'min', 'max', 'first', 'dense']) can be used to change how we want to rank the data

sorted_df

,Id,Name,Age,Country,Gender,Salary,Tax,New_Income,Ranking
0,1,John Doe,29.0,United States,M,55000.0,20%,60500.0,5.5
1,1,John Doe,29.0,United States,M,55000.0,20%,60500.0,5.5
2,2,Jane Smith,NaN,Canada,F,62000.0,10%,68200.0,8.5
3,3,Alex,NaN,United States,U,47000.0,20%,51700.0,3.0
4,4,Maria Garcia,34.0,Spain,F,25000.0,20%,NaN,1.0
5,5,Li Wei,27.0,China,M,51000.0,20%,56100.0,4.0
6,6,NaN,45.0,India,F,73000.0,10%,80300.0,11.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,10%,74800.0,10.0
8,8,Rachel Lee,29.0,United States,F,62000.0,10%,68200.0,8.5
9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,20%,49500.0,2.0
10,10,Emily Davis,31.0,United States,NaN,58000.0,20%,63800.0,7.0

In [ ]:
# Shift id column to the end
df3 = df.copy()
new_column_order = [col for col in df3 if col != "id"] + ["id"]

df3[new_column_order]

# OR we can also perform
# df3 = df.copy()
# id_col = df3.pop("id")   # removes the column together with its values
# df3["id"] = id_col      # adds it back at the end

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [ ]:
# Writing data in csv file

df4 = df.copy()

df4 = df4.drop_duplicates()
df4 = df4.fillna(0)
df4 = df4.sort_values("income")
df4 = df4.reset_index(drop=True)

df4.to_csv("sorted_data.csv")

In [40]:
df = pd.read_csv("raw_data.csv")

df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [41]:
# Grouping of data
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

# Aggregation
df.groupby("country")["income"].agg(["mean", "min", "max"])

#custom name
df.groupby("country")["income"].agg(avg_income="mean", min_income="min", max_income="max")

df.groupby("country").agg({
    "income": "mean",
    "age": "min"
})

# custom name
df.groupby("country").agg(
    avg_income= ("income", "mean"),
    min_age= ("age", "min")
)

         avg_income  min_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         55400.0     29.0